CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(32) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ADMIN','USER','RESELLER') NOT NULL DEFAULT 'USER',
  plan ENUM('BASIC','PREMIUM') NOT NULL DEFAULT 'BASIC',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cards (
  id VARCHAR(64) PRIMARY KEY,
  card_uid VARCHAR(64) NOT NULL UNIQUE,
  user_id VARCHAR(32) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  tap_count INT NOT NULL DEFAULT 0,
  redirect_mode ENUM('DIRECT','SMART') NOT NULL DEFAULT 'SMART',
  direct_google_url VARCHAR(512) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cards_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS profiles (
  id VARCHAR(64) PRIMARY KEY,
  user_id VARCHAR(32) NOT NULL,
  template_id VARCHAR(64) NULL,
  logo_url VARCHAR(512) NULL,
  primary_color VARCHAR(32) NULL,
  secondary_color VARCHAR(32) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS links (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(32) NOT NULL,
  type ENUM('GOOGLE','WHATSAPP','INSTAGRAM','WEBSITE') NOT NULL,
  url VARCHAR(512) NOT NULL,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_links_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS analytics_taps (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  card_uid VARCHAR(64) NOT NULL,
  tapped_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_taps_card (card_uid),
  INDEX idx_taps_time (tapped_at)
);

CREATE TABLE IF NOT EXISTS analytics_clicks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(32) NOT NULL,
  link_type ENUM('GOOGLE','WHATSAPP','INSTAGRAM','WEBSITE') NOT NULL,
  clicked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_clicks_user (user_id),
  INDEX idx_clicks_time (clicked_at)
);
